version: "3"

services:
  mysql:
    image: mysql:5.7
    command: --init-file /db/init.sql
    restart: always
    environment:
      - MYSQL_DATABASE=cars_crud
      - MYSQL_ROOT_PASSWORD=mypass
      - MYSQL_USER=root
    volumes:
      - ./db:/db
  api:
    build: ./api
    links:
      - mysql
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      - DB_URI=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASS=mypass
  webapp:
    build: ./webapp
    links:
      - api
    ports:
      - 3000:3000
    environment:
      - API_URI=api
      - API_PORT=8080