version: "3"

services:
  mysql:
    image: mysql:5.7
    command: mysqld --lower_case_table_names=1
    restart: always
    environment:
      - MYSQL_DATABASE=cars_crud
      - MYSQL_ROOT_PASSWORD=mypass
      - MYSQL_USER=root
    volumes:
      - ./db:/db
  api:
    build: ./api
    links:
      - mysql
    ports:
      - "8080:8080"
    depends_on:
      - mysql