version: "2"
services:
  mysql:
    image: mysql
    command: --init-file /db/init.sql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: "cars_crud"
      MYSQL_ROOT_PASSWORD: "mypass"
    volumes:
      - ./db:/db
    networks:
      - app_network
  admin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    ports:
      - 8000:80
    networks:
      - app_network
  api:
    build: ./api
    links:
      - mysql
    ports:
      - 8080:8080
    networks:
      - app_network
networks:
  app_network:
    driver: bridge