mysql:
  image: mysql
  ports:
    - 6603:3306
  environment:
    MYSQL_ROOT_PASSWORD: "mypass"
api:
  build: ./api
  links:
    - mysql
  ports:
    - 8080:8080
  environment:
    MYSQL_PASS: "mypass"
    HOST_URL: "0.0.0.0"
    HOST_PORT: 8080